### ISSUE TITLE
Pattern matching when crossing modules just matches the first option.

### ISSUE THREAD

**Issue by spott** [thautwarm/MLStyle.jl#102] opened 2020-11-06 23:11 UTC
When you define a ADT in one module, and try and match on it in another module, the first thing in the match statement is always returned.

    module A
       using MLStyle
       @data Data begin
         Data1
         Data2
         Data3
       end
       end

    module B
       using MLStyle
       import ..A
       function foo(x::A.Data)
         return @match x begin
           Data1 => "Data1"
           Data2 => "Data2"
           Data3 => "Data3"
         end
       end
       end

    B.foo(A.Data1) # returns "Data1"
    B.foo(A.Data2) # returns "Data1"
    B.foo(A.Data3) # returns "Data1"

I expect this is related to #100, but I thought I would post it here just to make sure.

**Comment by thautwarm** [comment] 2020-11-07 13:01
You can export those data constructors in A, and import them in B.

```julia
module A
   using MLStyle
   export Data1, Data2, Data3
   @data Data begin
     Data1
     Data2
     Data3
   end
   end

module B
   using MLStyle
   using ..A
   function foo(x::A.Data)
     return @match x begin
       Data1 => "Data1"
       Data2 => "Data2"
       Data3 => "Data3"
     end
   end
   end

B.foo(A.Data1) # returns "Data1"
B.foo(A.Data2) # returns "Data2"
B.foo(A.Data3) # returns "Data3"
```

There can be many data types named `Data1`, `Data2` or `Data3` in many other modules, Julia uses namespace to resolving the scope.

**Comment by thautwarm** [comment] 2020-12-06 05:33
@spott I feel like to close this, as it's not a bug.

Please note that the pattern deconstructor should be visible in current scope.
In your code, `Data1, 2, 3` is not imported in module B, hence they are treated as capture patterns.

**Closed** 2020-12-08 01:03 UTC
